### ISSUE TITLE
how redraw point

### ISSUE THREAD

**Issue by jecheverria** [JackZouShao/leaflet-marker-direction#3]
Hi, how redraw point or clear when not found points on _list_ on reload page
I desperate, thx.

**Comment by Thomas2077** [comment]
Remove layer:  demo like below  
```
 map.removeLayer(markerArray[i])
```
in [commit](https://github.com/Thomas2077/leaflet-marker-direction/commit/448b1e7ff250d1dc5e96ce7836fb1c313a912208#diff-70b09f45dadfc810335aaf4c2cf867f7b4bea714cf3f1ddf811472648cb6dd8b)
